#!/bin/bash

# Script para crear .env de router-psi desde .env.local

ENV_LOCAL="/opt/psi-vision-hub/.env.local"
ENV_ROUTER="/opt/psi-vision-hub/router-psi/.env"

echo "Creando .env para router-psi desde .env.local..."

# Leer variables de .env.local
source "$ENV_LOCAL" 2>/dev/null || true

# Crear .env para router-psi
cat > "$ENV_ROUTER" << EOF
# Servidor
NODE_ENV=production
PORT=3002
LOG_LEVEL=info
ANTILOOP_MINUTES=15

# Seguridad
WEBHOOK_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN}

# Supabase
SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_STORAGE_BUCKET_AUDIOS=${SUPABASE_STORAGE_BUCKET_AUDIOS:-audios}
SUPABASE_STORAGE_BUCKET_DOCUMENTOS=${SUPABASE_STORAGE_BUCKET_DOCUMENTOS:-documentos}

# WhatsApp Cloud API
WHATSAPP_TOKEN=${CLOUD_API_TOKEN}
CLOUD_API_BASE_URL=${CLOUD_API_BASE_URL}
WSP4_PHONE_ID=${CLOUD_API_PHONE_NUMBER_ID}
VENTAS1_PHONE_ID=${CLOUD_API_PHONE_NUMBER_ID}
ADMIN_PHONE_ID=${CLOUD_API_PHONE_NUMBER_ID}
ALUMNOS_PHONE_ID=${CLOUD_API_PHONE_NUMBER_ID}
COMUNIDAD_PHONE_ID=${CLOUD_API_PHONE_NUMBER_ID}
WSP4_NUMBER=5491156090819
VENTAS1_NUMBER=5491156090819

# Webhooks n8n
N8N_WEBHOOK_ENVIOS_ROUTER_CRM=${N8N_WEBHOOK_ENVIOS_ROUTER_CRM}
N8N_WEBHOOK_ENVIOS_ROUTER_ADMINISTRACION=${N8N_WEBHOOK_ENVIOS_ROUTER_ADMINISTRACION}
N8N_WEBHOOK_ENVIOS_ROUTER_ALUMNOS=${N8N_WEBHOOK_ENVIOS_ROUTER_ALUMNOS}
N8N_WEBHOOK_ENVIOS_ROUTER_COMUNIDAD=${N8N_WEBHOOK_ENVIOS_ROUTER_COMUNIDAD}
N8N_WEBHOOK_ENVIOS_ROUTER_VENTAS_1=${N8N_WEBHOOK_ENVIOS_ROUTER_VENTAS_1}
EOF

echo "✅ Archivo .env creado en: $ENV_ROUTER"
echo ""
echo "Verificando archivo..."
ls -la "$ENV_ROUTER"

